  elasticsearch56:
    image: elasticsearch:5.6.16
    command: elasticsearch
    ports:
      - '13200:9200'
      - '13300:9300'

  fake-elastic56-data:
    image: grafana/fake-data-gen
    links:
      - elasticsearch56
    environment:
      FD_SERVER: elasticsearch56
      FD_DATASOURCE: elasticsearch
      FD_PORT: 9200
