# You need to run 'sysctl -w vm.max_map_count=262144' on the host machine

  elasticsearch77:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    command: elasticsearch
    environment:
      - "discovery.type=single-node"
    ports:
      - "13200:9200"
      - "13300:9300"

  fake-elastic77-data:
    image: grafana/fake-data-gen
    links:
      - elasticsearch77
    environment:
      FD_SERVER: elasticsearch77
      FD_DATASOURCE: elasticsearch7
      FD_PORT: 9200

  filebeat77:
    image: docker.elastic.co/beats/filebeat:7.7.1
    command: filebeat -e -strict.perms=false
    volumes:
      - ./docker/blocks/elastic77/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/log:/var/log:ro
      - ../data/log:/var/log/grafana:ro

  metricbeat77:
    image: docker.elastic.co/beats/metricbeat:7.7.1
    command: metricbeat -e -strict.perms=false
    user: root
    volumes:
      - ./docker/blocks/elastic77/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  kibana77:
    image: docker.elastic.co/kibana/kibana:7.7.1
    ports:
      - "5601:5601"
    links:
      - elasticsearch77
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch77:9200
