version: '2'
services:
  web:
    build:
      context: grafana-8.2.6/grafana-8.2.6/
      dockerfile: Dockerfile
    links:
      - mysql
    ports:
      - "3000:3000"

    volumes:
      
      - ./app/grafana.ini:/etc/grafana/grafana.ini

  mysql:
    restart: always
    image: mysql:5.6
    container_name: web_mysql2

    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    environment:
      - "MYSQL_ROOT_PASSWORD=roothellotest123cve"
      - "MYSQL_DATABASE=grafana"
      - "TZ=Asia/Shanghai"


