# You need to run 'sysctl -w vm.max_map_count=262144' on the host machine

  elasticsearch-latest:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    command: elasticsearch
    environment:
      - "discovery.type=single-node"
    ports:
      - "14200:9200"
      - "14300:9300"

  fake-elastic-latest-data:
    image: grafana/fake-data-gen
    links:
      - elasticsearch-latest
    environment:
      FD_SERVER: elasticsearch-latest
      FD_DATASOURCE: elasticsearch7
      FD_PORT: 9200