  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    ports:
      - "6831:6831"
      - "3101:3101"
    volumes:
      - ./docker/blocks/tempo/tempo.yaml:/etc/tempo.yaml
