version: '3'
services:
  app:
    restart: always
    build: .
    depends_on:
      - mysql
    links:
      - mysql:mysql
    container_name: web_app1
    # volumes:
      # - ./app:/app
    ports:
    - "5002:5000"

  mysql:
    restart: always
    image: mysql:5.6
    container_name: web_mysql1

    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      

    environment:
      - "MYSQL_ROOT_PASSWORD=roothellotest123cve"
      - "MYSQL_DATABASE=ctf"
      - "TZ=Asia/Shanghai"
